version: 0.0
os: windows
files:
  - source: Default.aspx
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: scripts/before_install.bat
  AfterInstall:
    - location: scripts/after_install.bat