version: 0.0
os: windows
files:
  - source: PublishedWebsites/Default.aspx
    destination: C:\inetpub\wwwroot
  - source: PublishedWebsites/web.config
    destination: C:\inetpub\wwwroot
hooks:
  BeforeInstall:
    - location: scripts/before_install.bat
  AfterInstall:
    - location: scripts/after_install.bat