name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build with MSBuild
      run: msbuild MiProyectoDeploy.csproj -t:Publish -p:Configuration=Release -p:OutputPath=..\publish
    - name: List publish folder contents
      run: dir ./publish
    - name: Zip the publish folder
      run: Compress-Archive -Path ./publish/* -DestinationPath ./deploy.zip
    - name: Upload to S3
      run: aws s3 cp ./deploy.zip s3://mi-proyecto-deploy-2025/deploy.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Deploy with CodeDeploy
      run: aws deploy create-deployment --application-name MiProyectoDeployApp --deployment-group-name MiProyectoDeployGroup --s3-location bucket=mi-proyecto-deploy-2025,bundleType=zip,key=deploy.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}