name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: |
        if (-Not (Test-Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe")) {
          echo "MSBuild not found, check Visual Studio installation."
          exit 1
        }
        msbuild MiProyectoDeploy.csproj -t:Publish -p:Configuration=Release -p:OutDir=./publish

    - name: List publish folder contents
      run: Get-ChildItem ./publish

    - name: Zip the publish folder
      run: |
        if (!(Test-Path "./publish")) {
          echo "Publish folder does not exist. Build may have failed."
          exit 1
        }
        Compress-Archive -Path ./publish/* -DestinationPath ./deploy.zip

    - name: Install AWS CLI (if missing)
      run: |
        if (-Not (Get-Command "aws" -ErrorAction SilentlyContinue)) {
          echo "AWS CLI not found, installing..."
          choco install awscli -y
        }
        aws --version

    - name: Configure AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload to S3
      run: aws s3 cp ./deploy.zip s3://mi-proyecto-deploy-2025/deploy.zip --region us-east-1

    - name: Deploy with CodeDeploy
      run: aws deploy create-deployment --application-name MiProyectoDeployApp --deployment-group-name MiProyectoDeployGroup --s3-location bucket=mi-proyecto-deploy-2025,bundleType=zip,key=deploy.zip --region us-east-1
