name: Desplegar en EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    # Instalar .NET Framework 4.8
    - name: Instalar .NET Framework 4.8
      run: |
        Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?linkid=2088631" -OutFile "dotnet-framework-installer.exe"
        Start-Process -FilePath "dotnet-framework-installer.exe" -ArgumentList "/quiet /norestart" -Wait

    # Instalar Build Tools con componentes necesarios
    - name: Instalar Build Tools
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_BuildTools.exe" -OutFile "vs_BuildTools.exe"
        Start-Process -FilePath "vs_BuildTools.exe" -ArgumentList "--quiet --norestart --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Component.NuGet.BuildTools --add Microsoft.Net.Component.4.8.TargetingPack" -Wait

    # Encontrar ruta de MSBuild
    - name: Encontrar ruta de MSBuild
      id: msbuild
      run: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/vswhere/releases/download/3.1.1/vswhere.exe" -OutFile "vswhere.exe"
        $msbuildPath = .\vswhere.exe -latest -products * -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe"
        echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV

    # Compilar
    - name: Compilar con MSBuild
      run: ${{ env.MSBUILD_PATH }} MiProyectoDeploy.sln /p:Configuration=Release /p:OutputPath=./publish

    # Pasos siguientes (comprimir, subir a S3, etc.)
    - name: Comprimir la carpeta de publicación
      run: Compress-Archive -Path ./publish/* -DestinationPath ./deploy.zip
    - name: Subir a S3
      run: aws s3 cp ./deploy.zip s3://mi-proyecto-deploy-2025/deploy.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Desplegar con CodeDeploy
      run: aws deploy create-deployment --application-name MiProyectoDeployApp --deployment-group-name MiProyectoDeployGroup --s3-location bucket=mi-proyecto-deploy-2025,bundleType=zip,key=deploy.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}