name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build with MSBuild
      run: |
        echo "Verificando MSBuild..."
        Get-Command msbuild -ErrorAction Stop
        echo "Ejecutando MSBuild..."
        msbuild MiProyectoDeploy.csproj -t:Publish -p:Configuration=Release -p:PublishDir=./publish

    - name: Debug: Check publish directory
      shell: pwsh
      run: |
          if (Test-Path "./publish") {
            Write-Host "Publish folder exists."
          } else {
            Write-Host "ERROR: Publish folder does NOT exist."
            exit 1
          }
    - name: List publish folder contents
      run: Get-ChildItem ./publish
