name: SonarCloud Scan
on:
  push:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Install SonarScanner for MSBuild
      run: |
        New-Item -ItemType Directory -Path ".\sonarscanner" -Force
        $url = "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/9.2.1.110358/sonar-scanner-9.2.1.110358-net-framework.zip"
        $output = ".\sonarscanner\sonar-scanner.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath ".\sonarscanner" -Force
        # Listar contenido para depurar
        Write-Output "Contenido de sonarscanner:"
        dir .\sonarscanner\
        Write-Output "Contenido de subcarpetas:"
        Get-ChildItem -Path ".\sonarscanner" -Recurse
        # Verificar que el ejecutable exista
        if (-not (Test-Path ".\sonarscanner\SonarScanner.MSBuild.exe")) {
          throw "SonarScanner.MSBuild.exe no encontrado en la ruta esperada. Verifica la extracción."
        }
    - name: Begin SonarScanner Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        & ".\sonarscanner\SonarScanner.MSBuild.exe" begin /k:"MiProyectoDeploy" /o:"javierPerez123" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
    - name: Build Project
      run: |
        msbuild MiProyectoDeploy.sln /t:Rebuild
    - name: End SonarScanner Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        & ".\sonarscanner\SonarScanner.MSBuild.exe" end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"