name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Construir y analizar
    runs-on: windows-latest
    steps:
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Descargar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para un mejor análisis de ramas

      - name: Cachear paquetes de SonarCloud
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Instalar SonarScanner para MSBuild
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path ".\sonarscanner" -Force
          $url = "https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/9.2.1.110358/sonar-scanner-9.2.1.110358-net-framework.zip"
          $output = ".\sonarscanner\sonar-scanner.zip"
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath ".\sonarscanner" -Force
          if (-not (Test-Path ".\sonarscanner\SonarScanner.MSBuild.exe")) {
            throw "No se encontró SonarScanner.MSBuild.exe. Revisa la extracción."
          }

      - name: Iniciar análisis de SonarScanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          & ".\sonarscanner\SonarScanner.MSBuild.exe" begin /k:"MiProyectoDeploy" /o:"javierperez123" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanAllFiles="true" /d:sonar.branch.name="main" /d:sonar.verbose="true"

      - name: Construir proyecto
        shell: pwsh
        run: |
          msbuild MiProyectoDeploy.sln /t:Rebuild

      - name: Finalizar análisis de SonarScanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          & ".\sonarscanner\SonarScanner.MSBuild.exe" end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"